require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snipets from READMEs.
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - '**/*.gemspec'
    - '**/Rakefile'
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'
    - 'config/unicorn.rb'
    - 'config/puma.rb'
    - 'config/importmap.rb'
    - 'config.ru'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config/routes.rb'
    - 'node_modules/**/*'
    - 'Gemfile'

  NewCops: enable

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/Documentation:
  Enabled: false